# Generated by Django 5.2.5 on 2025-08-21 05:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0003_remove_nominee_votes_alter_nominee_category_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='vote',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='vote',
            name='category',
        ),
        migrations.RemoveField(
            model_name='vote',
            name='nominee',
        ),
        migrations.RemoveField(
            model_name='vote',
            name='user',
        ),
        migrations.AddField(
            model_name='nominee',
            name='votes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='nominee',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voting.category'),
        ),
        migrations.DeleteModel(
            name='CustomUser',
        ),
        migrations.DeleteModel(
            name='Vote',
        ),
    ]
